[metadata]
name = broken_access_control_scanner
version = 0.0.0
author = Steven van Gemert
author_email = steven@vangemert.dev
description = AI command line tool to detect broken access control vulnerabilities in source code
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/spmvg/broken_access_control_scanner
license = AGPL-3.0
classifiers =
  Development Status :: 4 - Beta
  License :: OSI Approved :: GNU Affero General Public License v3
  Programming Language :: Python :: 3

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.10
install_requires =
    typer
    anthropic
    rich

[options.packages.find]
where = src